/**
 * The shape of the published document, narrowed to what this site reads.
 *
 * These are structural types over a JSON artifact, not a model of OpenAPI 3.1.
 * The document is generated by `openapi/spec.ts` from the code that implements
 * it, so the vocabulary it can contain is finite and small — and
 * {@link assertKnownSchemaKeywords} makes the finiteness a checked property
 * rather than an assumption.
 */

export interface OpenApiSchema {
  readonly type?: string | readonly string[];
  readonly title?: string;
  readonly description?: string;
  readonly properties?: Readonly<Record<string, OpenApiSchema>>;
  readonly required?: readonly string[];
  readonly additionalProperties?: boolean;
  readonly enum?: readonly unknown[];
  readonly const?: unknown;
  readonly items?: OpenApiSchema;
  readonly $ref?: string;
  readonly minItems?: number;
  readonly maxItems?: number;
  readonly minimum?: number;
  readonly maximum?: number;
  readonly default?: unknown;
  readonly pattern?: string;
  readonly format?: string;
  readonly examples?: readonly unknown[];
}

export interface OpenApiParameter {
  readonly name: string;
  readonly in: string;
  readonly required?: boolean;
  readonly description?: string;
  readonly schema: OpenApiSchema;
}

export interface OpenApiResponse {
  readonly description?: string;
  readonly content?: Readonly<Record<string, { readonly schema?: OpenApiSchema }>>;
}

export interface OpenApiOperation {
  readonly operationId: string;
  readonly summary?: string;
  readonly description?: string;
  readonly tags?: readonly string[];
  readonly parameters?: readonly OpenApiParameter[];
  readonly responses: Readonly<Record<string, OpenApiResponse>>;
  readonly security?: readonly Readonly<Record<string, readonly string[]>>[];
}

export interface OpenApiDocument {
  readonly openapi: string;
  readonly info: {
    readonly title: string;
    readonly version: string;
    readonly summary?: string;
    readonly description?: string;
  };
  readonly servers?: readonly { readonly url: string; readonly description?: string }[];
  readonly tags?: readonly { readonly name: string; readonly description?: string }[];
  readonly security?: readonly Readonly<Record<string, readonly string[]>>[];
  readonly paths: Readonly<Record<string, Readonly<Record<string, OpenApiOperation>>>>;
  readonly components: {
    readonly schemas: Readonly<Record<string, OpenApiSchema>>;
    readonly securitySchemes?: Readonly<
      Record<string, { readonly type: string; readonly scheme?: string; readonly description?: string }>
    >;
  };
}

/** The HTTP methods a path item may carry. Read in this order, which is the order they render. */
export const HTTP_METHODS = ['get', 'put', 'post', 'delete', 'patch', 'head', 'options'] as const;

/**
 * Every schema keyword this site knows how to put on the page.
 *
 * ## Why an unknown keyword throws
 *
 * `openapi/schemaCheck.ts` throws on a validation keyword it does not implement,
 * because "a keyword that silently constrains nothing is a check that silently
 * stopped checking". The same argument applies with a sharper edge to a
 * *published reference*: a keyword this renderer skips is a constraint the
 * contract states and the documentation omits, read by an integrator who has no
 * way to know a cell is missing. A 400 they cannot explain is the cheap version
 * of that; building against a bound nobody told them about is the expensive one.
 *
 * So a new keyword in `spec.ts` fails the site build and names itself, and
 * somebody decides how it should read. That is a minute of work at the moment
 * the keyword is introduced, and the alternative is silence.
 */
export const KNOWN_SCHEMA_KEYWORDS = new Set([
  'type',
  'title',
  'description',
  'properties',
  'required',
  'additionalProperties',
  'enum',
  'const',
  'items',
  '$ref',
  'minItems',
  'maxItems',
  'minimum',
  'maximum',
  'default',
  'pattern',
  'format',
  'examples',
]);

export class UnknownSchemaKeywordError extends Error {
  constructor(keyword: string, where: string) {
    super(
      `schema keyword ${JSON.stringify(keyword)} at ${where} is not rendered by the ` +
        `documentation site. A constraint the contract states and the reference omits is one ` +
        `an integrator cannot know to satisfy — decide how it should read in ` +
        `docs/openApiDocument.ts rather than letting the page drop it.`
    );
    this.name = 'UnknownSchemaKeywordError';
  }
}

/**
 * Walk every schema reachable from the document and refuse an unrendered keyword.
 *
 * The descent follows only the two positions that hold a *schema* —
 * `properties.<name>` and `items`. It deliberately does not walk `enum`,
 * `const`, `default`, `examples` or `required`, whose contents are data: a
 * property called `id` or an enum value called `type` is not a keyword, and a
 * blind walk over every key in the subtree reports one as if it were.
 */
export function assertKnownSchemaKeywords(document: OpenApiDocument): void {
  const visit = (schema: OpenApiSchema, where: string): void => {
    for (const key of Object.keys(schema)) {
      if (!KNOWN_SCHEMA_KEYWORDS.has(key)) throw new UnknownSchemaKeywordError(key, where);
    }

    for (const [name, property] of Object.entries(schema.properties ?? {})) {
      visit(property, `${where}.properties.${name}`);
    }
    if (schema.items !== undefined) visit(schema.items, `${where}.items`);
  };

  for (const [name, schema] of Object.entries(document.components.schemas)) {
    visit(schema, `components.schemas.${name}`);
  }

  for (const [route, item] of Object.entries(document.paths)) {
    for (const method of HTTP_METHODS) {
      const operation = item[method];
      if (!operation) continue;
      for (const parameter of operation.parameters ?? []) {
        visit(parameter.schema, `${method.toUpperCase()} ${route} parameter ${parameter.name}`);
      }
      for (const [status, response] of Object.entries(operation.responses)) {
        for (const media of Object.values(response.content ?? {})) {
          if (media.schema) visit(media.schema, `${method.toUpperCase()} ${route} ${status}`);
        }
      }
    }
  }
}

const SCHEMA_REF_PREFIX = '#/components/schemas/';

/** `#/components/schemas/LoadRow` → `LoadRow`, or `null` for anything else. */
export function schemaRefName($ref: string): string | null {
  return $ref.startsWith(SCHEMA_REF_PREFIX) ? $ref.slice(SCHEMA_REF_PREFIX.length) : null;
}

/** The type names of a schema, normalised: 3.1 writes nullability as `["string", "null"]`. */
export function typeNames(schema: OpenApiSchema): readonly string[] {
  // Narrowed on `typeof`, not on `Array.isArray`, whose signature is
  // `arg is any[]` and so leaves `readonly string[]` in the negative branch.
  const { type } = schema;
  if (type === undefined) return [];
  return typeof type === 'string' ? [type] : type;
}

/**
 * One constraint, split into the prose part and the part that is a literal.
 *
 * Split rather than pre-formatted because `pattern` is a regular expression and
 * `default` is a JSON value, and both need to reach the page inside `<code>`:
 * `matching ^[A-Za-z]{2}$` set as prose reads as though the braces and the
 * dollar are punctuation in the sentence. The renderer decides the markup; this
 * decides what the words are.
 */
export interface ConstraintPhrase {
  readonly text: string;
  /** Set verbatim, in a code span, after {@link text}. */
  readonly code: string | null;
}

/**
 * The constraints on a schema, as short phrases, in a fixed order.
 *
 * Fixed rather than object-key order because the published page must be the
 * same bytes on a laptop and on a host — the same reason `changelogHtml.ts`
 * slices its timestamps instead of formatting them.
 */
export function constraintPhrases(schema: OpenApiSchema): ConstraintPhrase[] {
  const phrases: ConstraintPhrase[] = [];
  const push = (text: string, code: string | null = null): void => {
    phrases.push({ text, code });
  };

  if (schema.const !== undefined) push('always', JSON.stringify(schema.const));
  if (schema.format !== undefined) push('format', schema.format);
  if (schema.pattern !== undefined) push('matching', schema.pattern);

  if (schema.minimum !== undefined && schema.maximum !== undefined) {
    push(`${schema.minimum} to ${schema.maximum}`);
  } else if (schema.minimum !== undefined) {
    push(`at least ${schema.minimum}`);
  } else if (schema.maximum !== undefined) {
    push(`at most ${schema.maximum}`);
  }

  if (schema.minItems !== undefined) push(`at least ${schema.minItems} item(s)`);
  if (schema.maxItems !== undefined) push(`at most ${schema.maxItems} item(s)`);
  if (schema.default !== undefined) push('default', JSON.stringify(schema.default));

  return phrases;
}

export interface FlattenedProperty {
  /** Dotted path from the root of the schema — `meta.coverage`. */
  readonly path: string;
  readonly schema: OpenApiSchema;
  /** True only when every level of the path is required by its parent. */
  readonly required: boolean;
}

/**
 * An object schema's properties as a flat list of dotted paths.
 *
 * **Inline objects flatten; named schemas link.** `ObservationsLoadResponse`
 * declares `meta` inline with fourteen fields under it, and a nested table
 * inside a table cell is unreadable in a page with no stylesheet to lay it out.
 * `meta.coverage` is also how an integrator refers to the field out loud and how
 * they reach it in code, so the flattened form is the one that matches the thing
 * being described. A `$ref` stops the descent — `LoadRow` is documented once, in
 * its own section, and linked from every response that returns it, rather than
 * copied into six tables that can drift apart.
 *
 * `required` is conjunctive down the path: `meta.zone` is only required if `meta`
 * is required too. An optional object's mandatory field is not a field the
 * caller can count on, and marking it required would say they could.
 */
export function flattenProperties(schema: OpenApiSchema): FlattenedProperty[] {
  const out: FlattenedProperty[] = [];

  const descend = (node: OpenApiSchema, prefix: string, inherited: boolean): void => {
    const required = new Set(node.required ?? []);
    for (const [name, property] of Object.entries(node.properties ?? {})) {
      const path = prefix === '' ? name : `${prefix}.${name}`;
      const isRequired = inherited && required.has(name);
      out.push({ path, schema: property, required: isRequired });

      const isInlineObject =
        property.$ref === undefined &&
        property.properties !== undefined &&
        typeNames(property).includes('object');
      if (isInlineObject) descend(property, path, isRequired);
    }
  };

  descend(schema, '', true);
  return out;
}
